
package javaassignment.Admin.SM;

import javaassignment.Admin.AdminMainPage;
import javaassignment.SalesManager.DailyItemEntryPage_SM;
import javaassignment.SalesManager.SalesReportPage_SM;
import javaassignment.SalesManager.ViewSalesItemPage_SM;

/**
 *
 * @author vroom
 */
public class AdminSMPage extends javax.swing.JFrame {

    /**
     * Creates new form SalesManagerMainPage
     */
    public AdminSMPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Back_BTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ViewSalesItem_BTN = new javax.swing.JButton();
        DailyItemSalesEntry_BTN = new javax.swing.JButton();
        SalesReport_BTN = new javax.swing.JButton();
        ViewPurchaseOrder_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sales Manager Main");

        Back_BTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back_BTN.setText("Back");
        Back_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(Back_BTN)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        ViewSalesItem_BTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewSalesItem_BTN.setText("View Sales Items & Create Requisition");
        ViewSalesItem_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSalesItem_BTNActionPerformed(evt);
            }
        });

        DailyItemSalesEntry_BTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DailyItemSalesEntry_BTN.setText("Daily Item-wise Sales Entry");
        DailyItemSalesEntry_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyItemSalesEntry_BTNActionPerformed(evt);
            }
        });

        SalesReport_BTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SalesReport_BTN.setText("Sales Report");
        SalesReport_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesReport_BTNActionPerformed(evt);
            }
        });

        ViewPurchaseOrder_BTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewPurchaseOrder_BTN.setText("View Purchaser Orders");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ViewSalesItem_BTN)
                        .addGap(91, 91, 91)
                        .addComponent(DailyItemSalesEntry_BTN))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SalesReport_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(ViewPurchaseOrder_BTN)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewSalesItem_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DailyItemSalesEntry_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewPurchaseOrder_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalesReport_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 870, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BTNActionPerformed
        AdminMainPage AMP = new AdminMainPage();
        AMP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_BTNActionPerformed

    private void ViewSalesItem_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSalesItem_BTNActionPerformed
       ViewSalesItemPage_SM VSIT = new ViewSalesItemPage_SM();
       VSIT.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ViewSalesItem_BTNActionPerformed

    private void DailyItemSalesEntry_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyItemSalesEntry_BTNActionPerformed
       DailyItemEntryPage_SM DIE = new DailyItemEntryPage_SM();
       DIE.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_DailyItemSalesEntry_BTNActionPerformed

    private void SalesReport_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesReport_BTNActionPerformed
       SalesReportPage_SM SR = new SalesReportPage_SM();
       SR.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_SalesReport_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSMPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSMPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSMPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSMPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSMPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_BTN;
    private javax.swing.JButton DailyItemSalesEntry_BTN;
    private javax.swing.JButton SalesReport_BTN;
    private javax.swing.JButton ViewPurchaseOrder_BTN;
    private javax.swing.JButton ViewSalesItem_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
