
package javaassignment.Admin;

import javaassignment.Admin.AdminDAOImpl;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;


public class EditUser extends javax.swing.JFrame {
   private String loggedInUser;
   private User user;

    /** Creates new form UpdateUser */
    public EditUser(User user) {
        initComponents();
        this.user = user;
        this.loggedInUser = loggedInUser;
        
        ID_TF.setText(user.getUserId());
        FName_TF.setText(user.getFullName());
        ICNum_TF.setText(user.getIcNumber());
        Password_TF.setText(user.getPassword());
        email_TF.setText(user.getEmail());
        PN_TF.setText(user.getPhNumber());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID_TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FName_TF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Password_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email_TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PN_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ICNum_TF = new javax.swing.JTextField();
        Save_BTN = new javax.swing.JButton();
        Back_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Update User Details");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Full Name ");

        ID_TF.setBackground(new java.awt.Color(204, 204, 204));
        ID_TF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ID_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_TFActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("IC Number ");

        FName_TF.setBackground(new java.awt.Color(204, 204, 204));
        FName_TF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password");

        Password_TF.setBackground(new java.awt.Color(204, 204, 204));
        Password_TF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Password_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TFActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");

        email_TF.setBackground(new java.awt.Color(204, 204, 204));
        email_TF.setForeground(new java.awt.Color(0, 0, 0));
        email_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_TFActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Phone Number");

        PN_TF.setBackground(new java.awt.Color(204, 204, 204));
        PN_TF.setForeground(new java.awt.Color(0, 0, 0));
        PN_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PN_TFActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("User ID");

        ICNum_TF.setBackground(new java.awt.Color(204, 204, 204));
        ICNum_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICNum_TFActionPerformed(evt);
            }
        });

        Save_BTN.setText("Save");
        Save_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_BTNActionPerformed(evt);
            }
        });

        Back_BTN.setText("Back");
        Back_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ID_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FName_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Password_TF)
                                    .addComponent(email_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PN_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ICNum_TF))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(Save_BTN)))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Back_BTN)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_BTN)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FName_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addComponent(ICNum_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Password_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PN_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Save_BTN)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_TFActionPerformed

    private void email_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_TFActionPerformed

    private void PN_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PN_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PN_TFActionPerformed

    private void Save_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_BTNActionPerformed
        // Get the updated details from the text fields
    String updatedFullName = FName_TF.getText();
    String updatedIcNumber = ICNum_TF.getText();
    String updatedPassword = Password_TF.getText();
    String updatedEmail = email_TF.getText();
    String updatedPhoneNumber = PN_TF.getText();

    // Update the user object
    user.setFullName(updatedFullName);
    user.setIcNumber(updatedIcNumber);
    user.setPassword(updatedPassword);
    user.setEmail(updatedEmail);
    user.setPhNumber(updatedPhoneNumber);

    // Call the update method from the AdminDAOImpl to save the updated details
    AdminDAOImpl adminDAO = new AdminDAOImpl();  // Assuming you have access to AdminDAOImpl
    boolean isUpdated = adminDAO.updateUser(user);

    if (isUpdated) {
        // Optionally, show a message confirming the update
        JOptionPane.showMessageDialog(this, "User details updated successfully!");
    } else {
        // Handle the case where the user was not found or update failed
        JOptionPane.showMessageDialog(this, "User update failed or user not found.");
    }
    }//GEN-LAST:event_Save_BTNActionPerformed

    private void Back_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BTNActionPerformed
        UsersList UL = new UsersList();
        UL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_BTNActionPerformed

    private void ICNum_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICNum_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ICNum_TFActionPerformed

    private void Password_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TFActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            User user = new User(); // Initialize appropriately
            new EditUser(user).setVisible(true);
            }
        });
    }
    
    private void saveUserToFile(User user) {
        try {
        String filePath = "src/Databases/USERS.TXT";
        File file = new File(filePath);

        // Check if the file exists
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "User data file not found. Creating new file.", "Info", JOptionPane.INFORMATION_MESSAGE);
            file.createNewFile();  // Create the file if it doesn't exist
        }

        BufferedReader reader = new BufferedReader(new FileReader(file));
        StringBuilder fileContent = new StringBuilder();
        String line;
        boolean isUpdated = false;

        // Read all lines and modify the matching one
        while ((line = reader.readLine()) != null) {
            String[] userData = line.split(","); // Assuming CSV format
            if (userData.length > 0 && userData[0].trim().equals(user.getUserId())) { // Match user ID
                // Replace the line with updated user data
                line = user.getUserId() + "," + user.getFullName() + "," + user.getIcNumber() + ","
                       + user.getPassword() + "," + user.getEmail() + "," + user.getPhNumber();
                isUpdated = true;
            }
            fileContent.append(line).append("\n");
        }
        reader.close();

        if (!isUpdated) {
            JOptionPane.showMessageDialog(this, "User ID not found in the file.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Write updated content back to the file
        BufferedWriter writer = new BufferedWriter(new FileWriter(file, false)); // Overwrite the file
        writer.write(fileContent.toString().trim()); // Remove the last newline character
        writer.close();

        JOptionPane.showMessageDialog(this, "User details updated successfully!");

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving user details: " + e.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_BTN;
    private javax.swing.JTextField FName_TF;
    private javax.swing.JTextField ICNum_TF;
    private javax.swing.JTextField ID_TF;
    private javax.swing.JTextField PN_TF;
    private javax.swing.JTextField Password_TF;
    private javax.swing.JButton Save_BTN;
    private javax.swing.JTextField email_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
